Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2020-12, with the labels that each got.

#166 Update setup-kind Github action
  .github/workflows/old-operator.yaml
  .github/workflows/test.yaml
Labels: chore

#170 Fw port 0.11 changes
  .github/workflows/helm.yaml
  .github/workflows/old-operator.yaml
  .github/workflows/test.yaml
Labels: chore

#165 Let the user set the installation namespace for operator helm chart
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/templates/manager.yaml
  charts/astarte-operator/templates/rbac.yaml
  charts/astarte-operator/values.yaml
Labels: bug, minor

#172 Fix `make deploy`
  Makefile
Labels: bug, minor

#171 Fix chart templating
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/crds/crds.yaml
  config/helm-manager/kustomization.yaml
  config/helm-rbac/kustomization.yaml
  config/manager/manager.yaml
Labels: blocking, bug

#175 vernemq: allow using the mirror queue feature
  CHANGELOG.md
  deploy/crds/api.astarte-platform.org_astartes_crd.yaml
  pkg/apis/api/v1alpha1/astarte_types.go
  pkg/controller/astarte/reconcile/vernemq.go
Labels: enhancement

#180 Update zz_generated files
  apis/api/v1alpha1/zz_generated.deepcopy.go
  apis/api/v1alpha2/zz_generated.deepcopy.go
Labels: bug

#176 examples: wrap CPU quotas in single quotes
  deploy/examples/api_v1alpha1_astarte_cr_minimal.yaml
Labels: minor, user experience
