Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2020-05, with the labels that each got.

#109 Fix missing flow ingress in default deployments
  pkg/misc/utils.go
Labels: bug

#110 Add DATA_UPDATER_PLANT_AMQP_DATA_QUEUE_TOTAL_COUNT
  CHANGELOG.md
  pkg/controller/astarte/reconcile/astarte_generic_backend.go
Labels: blocking, enhancement

#111 Prepare 0.11.1 release
  CHANGELOG.md
  test/e2e010/test_upgrade_0.11.go
  test/e2e011/test_deploy_0.11.go
  test/utils/astarte_resource.go
  version/version.go
Labels: chore
