Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2020-09, with the labels that each got.

#151 Bump version number
  CHANGELOG.md
  test/e2e010/test_upgrade_0.11.go
  test/e2e011/test_deploy_0.11.go
  test/utils/astarte_resource.go
  version/version.go
Labels: chore

#153 Fix deployment strategy
  pkg/apis/api/v1alpha1/astarte_types.go
  pkg/apis/api/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/astarte/reconcile/astarte_dashboard.go
  pkg/controller/astarte/reconcile/astarte_generic_api.go
  pkg/controller/astarte/reconcile/astarte_generic_backend.go
  pkg/controller/astarte/reconcile/utils.go
  test/utils/astarte_resource.go
Labels: critical

#154 Update changelog
  CHANGELOG.md
Labels: chore

#156 Trigger Engine: fix deployment strategy
  CHANGELOG.md
  pkg/controller/astarte/reconcile/utils.go
Labels: blocking

#157 Forward port changes from release-0.11
  CHANGELOG.md
  api/v1alpha1/astarte_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  lib/reconcile/astarte_dashboard.go
  lib/reconcile/astarte_generic_api.go
  lib/reconcile/astarte_generic_backend.go
  lib/reconcile/utils.go
  test/utils/astarte_resource.go
Labels: chore

#158 Flow: fix deployment strategy
  CHANGELOG.md
  lib/reconcile/utils.go
Labels: blocking
