Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2021-01, with the labels that each got.

#169 Fix HTTP-01 challenge failure
  pkg/controller/astartevoyageringress/api_ingress.go
  pkg/controller/astartevoyageringress/broker_ingress.go
Labels: bug

#186 Fwport from 0.11
  lib/voyager/api_ingress.go
  lib/voyager/broker_ingress.go
Labels: chore

#187 Add linter capability to makefile
  Makefile
  go.mod
  go.sum
Labels: enhancement

#188 Use logfmt
  CHANGELOG.md
  go.mod
  go.sum
  main.go
Labels: chore

#190 Prepare v0.11.4
  CHANGELOG.md
  test/e2e010/test_upgrade_0.11.go
  test/e2e011/test_deploy_0.11.go
  test/utils/astarte_resource.go
  version/version.go
Labels: chore
