Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2021-03, with the labels that each got.

#199 Update dependencies
  .github/workflows/golangci-lint.yaml
  CHANGELOG.md
  Makefile
  PROJECT
  controllers/api/astarte_finalizer.go
  go.mod
  go.sum
Labels: chore

#200 astarte_common_types: add AdditionalEnv field
  CHANGELOG.md
  apis/api/commontypes/astarte_common_types.go
  apis/api/commontypes/zz_generated.deepcopy.go
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/templates/crds.yaml
  charts/astarte-operator/values.yaml
  config/crd/bases/api.astarte-platform.org_astartes.yaml
  lib/reconcile/utils.go
Labels: enhancement

#202 Add minimal sample cr
  CHANGELOG.md
  deploy/samples/api_v1alpha2_astarte_cr_minimal.yaml
  deploy/samples/api_v1alpha2_astarte_voyager_ingress_cr_minimal.yaml
Labels: user experience

#204 Tear down CFSSL StatefulSet when upgrading Astarte 0.11 -> 1.0
  CHANGELOG.md
  lib/upgrade/0.11_to_1.0.go
  lib/upgrade/operations.go
Labels: bug, minor

#208 Update cfssl default version
  CHANGELOG.md
  lib/deps/dependencies_versions.go
Labels: chore

#207 CI: Update KinD action and push operator's container to local KinD registry
  .github/workflows/helm.yaml
  .github/workflows/old-operator.yaml
  .github/workflows/test.yaml
Labels: enhancement, testing

#206 Update rabbitmq default version to 3.8.14
  CHANGELOG.md
  lib/deps/dependencies_versions.go
Labels: chore

#210 CI: install the chart with `helm install` instead of `ct install`
  .github/workflows/helm.yaml
Labels: bug

#209 Prepare 1.0.0-beta.2
  CHANGELOG.md
  Makefile
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/values.yaml
  deploy/samples/api_v1alpha2_astarte_cr_minimal.yaml
  lib/upgrade/0.11_to_1.0.go
  test/e2e011/astarte_0.11_test.go
  test/e2e10/deploy_astarte_1.0_test.go
  test/helm/astarte.yaml
  version/version.go
Labels: chore

#211 Forward-port changes from 1.0
  .github/workflows/helm.yaml
  .github/workflows/old-operator.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  Makefile
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/values.yaml
  deploy/samples/api_v1alpha2_astarte_cr_minimal.yaml
  lib/deps/dependencies_versions.go
  lib/upgrade/0.11_to_1.0.go
  lib/upgrade/operations.go
  test/e2e011/astarte_0.11_test.go
  test/e2e10/deploy_astarte_1.0_test.go
  test/helm/astarte.yaml
  version/version.go
Labels: chore
