Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2021-02, with the labels that each got.

#185 Define common types and CRD conversions
  CHANGELOG.md
  apis/api/commontypes/astarte_common_types.go
  apis/api/commontypes/astartevoyageringress_common_types.go
  apis/api/commontypes/flow_common_types.go
  apis/api/commontypes/zz_generated.deepcopy.go
  apis/api/v1alpha1/astarte_types.go
  apis/api/v1alpha1/astarte_webhook.go
  apis/api/v1alpha1/astartevoyageringress_types.go
  apis/api/v1alpha1/conversion.go
  apis/api/v1alpha1/flow_types.go
  apis/api/v1alpha1/webhook.go
  apis/api/v1alpha1/zz_generated.deepcopy.go
  apis/api/v1alpha2/astarte_conversion.go
  apis/api/v1alpha2/astarte_types.go
  apis/api/v1alpha2/astartevoyageringress_types.go
  apis/api/v1alpha2/conversion.go
  apis/api/v1alpha2/flow_types.go
  apis/api/v1alpha2/zz_generated.deepcopy.go
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/templates/crds.yaml
  charts/astarte-operator/templates/webhook.yaml
  config/crd/bases/api.astarte-platform.org_astartes.yaml
  config/crd/bases/api.astarte-platform.org_astartevoyageringresses.yaml
  config/crd/bases/api.astarte-platform.org_flows.yaml
  config/webhook/manifests.yaml
  controllers/api/astarte_controller.go
  controllers/api/flow_controller.go
  go.mod
  go.sum
  lib/controllerutils/astarte_controller.go
  lib/flow/block.go
  lib/misc/utils.go
  lib/reconcile/astarte_dashboard.go
  lib/reconcile/astarte_generic_api.go
  lib/reconcile/astarte_generic_backend.go
  lib/reconcile/cassandra.go
  lib/reconcile/cfssl.go
  lib/reconcile/rabbitmq.go
  lib/reconcile/utils.go
  lib/reconcile/vernemq.go
  lib/upgrade/0.10_to_0.11.go
  lib/upgrade/0.11_to_1.0.go
  lib/upgrade/operations.go
  lib/upgrade/upgrade.go
  lib/voyager/api_ingress.go
  main.go
  test/e2e010/astarte_0.10_test.go
  test/e2e011/astarte_0.11_test.go
  test/e2e10/deploy_astarte_1.0_test.go
  test/oldoperator/astarte_retrocompat_test.go
  test/utils/astarte_resource.go
  test/utils/function_blocks.go
Labels: blocking, enhancement

#189 Add script to automate operations while upgrading 0.11 --> 1.0
  hack/upgrade-operator-011-10.sh
Labels: blocking

#192 Update default chart's operator tag and bump chart version
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/values.yaml
Labels: bug

#193 flow_common_types: make RabbitMQConfig actually optional
  apis/api/commontypes/flow_common_types.go
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/values.yaml
  config/manager/manager.yaml
Labels: bug, enhancement

#194 Remove redundant annotations
  hack/upgrade-operator-011-10.sh
Labels: bug

#195 block: allow container blocks to run as root
  lib/flow/block.go
Labels: user experience

#191 Update README
  README.md
Labels: blocking

#196 Disable ReadyOnlyRootFilesystem
  lib/flow/block.go
Labels: user experience

#197 Prepare 1.0.0-beta.1
  CHANGELOG.md
  Makefile
  lib/upgrade/0.11_to_1.0.go
  test/e2e011/astarte_0.11_test.go
  test/e2e10/deploy_astarte_1.0_test.go
  test/utils/astarte_resource.go
  version/version.go
Labels: chore

#198 Prepare chart for 1.0.0-beta.1
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/values.yaml
  test/helm/astarte.yaml
Labels: chore
