Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2022-02, with the labels that each got.

#257 Fix naming for the chart
  charts/astarte-operator/Chart.yaml
Labels: bug, minor

#256 Upgrade OperatorSDK
  .github/workflows/test.yaml
  .gitignore
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
  apis/api/commontypes/zz_generated.deepcopy.go
  apis/api/v1alpha1/webhook.go
  apis/api/v1alpha1/zz_generated.deepcopy.go
  apis/api/v1alpha2/zz_generated.deepcopy.go
  apis/ingress/v1alpha1/zz_generated.deepcopy.go
  charts/astarte-operator/templates/crds.yaml
  charts/astarte-operator/templates/manager.yaml
  charts/astarte-operator/templates/rbac.yaml
  charts/astarte-operator/templates/webhook.yaml
  config/crd/bases/_.yaml
  config/crd/bases/api.astarte-platform.org_astartes.yaml
  config/crd/bases/api.astarte-platform.org_astartevoyageringresses.yaml
  config/crd/bases/api.astarte-platform.org_flows.yaml
  config/crd/bases/ingress.astarte-platform.org_astartedefaultingresses.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  lib/reconcile/astarte_generic_api.go
  lib/reconcile/astarte_generic_backend.go
  lib/reconcile/cassandra.go
  lib/reconcile/cfssl.go
  lib/reconcile/rabbitmq.go
  lib/reconcile/vernemq.go
  lib/upgrade/operations.go
Labels: chore

#235 Remove commontypes and automate CRD conversion functions generation
  CHANGELOG.md
  Makefile
  README.md
  apis/api/commontypes/astarte_common_types.go
  apis/api/commontypes/astartevoyageringress_common_types.go
  apis/api/commontypes/flow_common_types.go
  apis/api/commontypes/zz_generated.deepcopy.go
  apis/api/v1alpha1/astarte_types.go
  apis/api/v1alpha1/astartevoyageringress_types.go
  apis/api/v1alpha1/doc.go
  apis/api/v1alpha1/flow_types.go
  apis/api/v1alpha1/register.go
  apis/api/v1alpha1/zz_generated.deepcopy.go
  apis/api/v1alpha2/astarte_types.go
  apis/api/v1alpha2/astartevoyageringress_types.go
  apis/api/v1alpha2/conversion.go
  apis/api/v1alpha2/doc.go
  apis/api/v1alpha2/flow_types.go
  apis/api/v1alpha2/register.go
  apis/api/v1alpha2/zz_generated.conversion.go
  apis/api/v1alpha2/zz_generated.deepcopy.go
  controllers/api/astarte_controller.go
  controllers/api/flow_controller.go
  lib/controllerutils/astarte_controller.go
  lib/defaultingress/api_ingress.go
  lib/flow/block.go
  lib/misc/utils.go
  lib/reconcile/astarte_dashboard.go
  lib/reconcile/astarte_data_updater_plant.go
  lib/reconcile/astarte_generic_api.go
  lib/reconcile/astarte_generic_backend.go
  lib/reconcile/cassandra.go
  lib/reconcile/cfssl.go
  lib/reconcile/rabbitmq.go
  lib/reconcile/utils.go
  lib/reconcile/vernemq.go
  lib/upgrade/0.11_to_1.0.go
  lib/upgrade/operations.go
  lib/upgrade/upgrade.go
  lib/voyager/api_ingress.go
  test/e2e011/astarte_0.11_test.go
  test/e2e10/deploy_astarte_1.0_test.go
  test/utils/astarte_resource.go
  test/utils/function_blocks.go
Labels: enhancement
