Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2023-05, with the labels that each got.

#326 Prepare 23.05.00-dev release cycle
  .github/workflows/test.yaml
  CHANGELOG.md
  Makefile
  README.md
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/values.yaml
  docs/documentation/mix.exs
  lib/controllerutils/astarte_controller.go
  lib/upgrade/0.11_to_1.0.go
  lib/upgrade/operations.go
  lib/upgrade/upgrade.go
  test/e2e011/astarte_0.11_test.go
  test/e2e011/astarte_test.go
  test/utils/astarte_resource.go
  version/version.go
Labels: chore

#323 Restart the broker when its SSLListener secret changes
  CHANGELOG.md
  charts/astarte-operator/templates/rbac.yaml
  config/rbac/role.yaml
  controllers/api/astarte_controller.go
  lib/reconcile/vernemq.go
Labels: enhancement, user experience

#325 Implement minor fixes for the docs
  .github/workflows/generate-docs.yaml
  docs/documentation/mix.exs
  docs/documentation/pages/crds/001-intro_crds.md
Labels: documentation

#327 Update OperatorSDK to v1.27.0
  .tool-versions
  CHANGELOG.md
  Makefile
  README.md
  apis/ingress/v1alpha1/webhook_suite_test.go
  charts/astarte-operator/templates/crds.yaml
  config/crd/bases/_.yaml
  config/crd/bases/api.astarte-platform.org_astartes.yaml
  config/crd/bases/api.astarte-platform.org_astartevoyageringresses.yaml
  config/crd/bases/api.astarte-platform.org_flows.yaml
  config/crd/bases/ingress.astarte-platform.org_astartedefaultingresses.yaml
  controllers/api/suite_test.go
  controllers/ingress/suite_test.go
  go.mod
  go.sum
  test/e2e10/astarte_test.go
  test/e2e10/deploy_astarte_1.0_test.go
  test/e2e11/astarte_test.go
  test/e2e11/deploy_astarte_1.1_test.go
Labels: chore
