Repository astarte-platform/astarte-kubernetes-operator, pull requests merged in 2024-01, with the labels that each got.

#350 Upgrade dependencies and fix vulnerabilities
  .tool-versions
  Makefile
  apis/ingress/v1alpha1/webhook_suite_test.go
  charts/astarte-operator/templates/crds.yaml
  config/crd/bases/_.yaml
  config/crd/bases/api.astarte-platform.org_astartes.yaml
  config/crd/bases/api.astarte-platform.org_astartevoyageringresses.yaml
  config/crd/bases/api.astarte-platform.org_flows.yaml
  config/crd/bases/ingress.astarte-platform.org_astartedefaultingresses.yaml
  config/default/manager_auth_proxy_patch.yaml
  go.mod
  go.sum
Labels: chore

#357 Prepare 23.5.1 release
  CHANGELOG.md
  Makefile
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/values.yaml
  docs/documentation/mix.exs
  version/version.go
Labels: chore

#358 Fix broken links in documentation pages
  docs/documentation/pages/administrator/040-manual_kubernetes.md
  docs/documentation/pages/administrator/060-setup_cluster.md
  docs/documentation/pages/administrator/064-setup_astartedefaultingress.md
  docs/documentation/pages/upgrade/040-upgrade_10x_2211.md
  docs/documentation/pages/upgrade/050-upgrade_2211_235.md
Labels: chore, documentation

#360 Forward port changes from release-23.5
  .github/workflows/generate-docs.yaml
  .tool-versions
  CHANGELOG.md
  Makefile
  apis/ingress/v1alpha1/webhook_suite_test.go
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/templates/crds.yaml
  charts/astarte-operator/values.yaml
  config/crd/bases/_.yaml
  config/crd/bases/api.astarte-platform.org_astartes.yaml
  config/crd/bases/api.astarte-platform.org_astartevoyageringresses.yaml
  config/crd/bases/api.astarte-platform.org_flows.yaml
  config/crd/bases/ingress.astarte-platform.org_astartedefaultingresses.yaml
  config/default/manager_auth_proxy_patch.yaml
  docs/autogen/config.yaml
  docs/documentation/pages/administrator/040-manual_kubernetes.md
  docs/documentation/pages/administrator/060-setup_cluster.md
  docs/documentation/pages/administrator/064-setup_astartedefaultingress.md
  docs/documentation/pages/upgrade/000-upgrade_index.md
  docs/documentation/pages/upgrade/040-upgrade_10x_2211.md
  docs/documentation/pages/upgrade/050-upgrade_2211_235.md
  go.mod
  go.sum
  lib/reconcile/utils.go
  version/version.go
Labels: chore

#361 Prepare 23.11.0-dev release cycle
  CHANGELOG.md
  Makefile
  README.md
  SECURITY.md
  charts/astarte-operator/Chart.yaml
  charts/astarte-operator/values.yaml
  docs/documentation/mix.exs
  go.sum
  version/version.go
Labels: chore

#359 Do not template CRDs
  CHANGELOG.md
  Makefile
  charts/astarte-operator/crds/astartedefaultingresses.ingress.astarte-platform.org.yaml
  charts/astarte-operator/crds/astartes.api.astarte-platform.org.yaml
  charts/astarte-operator/crds/astartevoyageringresses.api.astarte-platform.org.yaml
  charts/astarte-operator/crds/flows.api.astarte-platform.org.yaml
  charts/astarte-operator/templates/crds.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/helm-crd/kustomization.yaml
  config/helm-crd/service-name-helm_patch.yaml
Labels: enhancement

#362 Update maintainers list
  AUTHORS.md
  charts/astarte-operator/Chart.yaml
  config/manifests/bases/astarte-kubernetes-operator.clusterserviceversion.yaml
Labels: chore

#363 Docs: update CRD reference generation tool
  Makefile
Labels: chore

#364 Bump tool versions in CI
  .github/workflows/codeql-analysis.yaml
  .github/workflows/generate-docs.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/helm-sync.yaml
  .github/workflows/helm.yaml
  .github/workflows/image-test.yaml
  .github/workflows/test.yaml
  README.md
  docs/documentation/pages/administrator/001-intro_administrator.cheatmd
  docs/documentation/pages/administrator/020-prerequisites.md
Labels: chore
